### ISSUE TITLE
Problem with launching the script which crashes after selecting a target

### ISSUE THREAD

**Issue by thepoulet153** [pentestfunctions/BlueDucky#20]
![Screenshot_2024-03-30_07_40_10](https://github.com/pentestfunctions/BlueDucky/assets/64045692/cb097f15-9365-4d93-9891-2272a85ad524)

Hello everyone, I have a problem with launching the script which crashes after selecting a target.
I'm on: Linux kali-raspberry-pi 5.15.44-Re4son-v8l+ #1 SMP PREEMPT Debian kali-pi (2022-07-03) aarch64 GNU/Linux
Release: 2024.1
Thanks in advance

**Comment by PhucHauDeveloper** [comment]
Try rebooting if you just installed it

**Comment by thepoulet153** [comment]
It doesn't work, still the same error :[

**Comment by thepoulet153** [comment]
It's okay, I solved my problem with my little hands and a few python magic tricks, the problem comes from the fact that the Bluetooth takes too long to restart, so I added a delay ;)

**Comment by thepoulet153** [comment]
It's okay, I solved my problem with my little hands and a few python magic tricks, the problem comes from the fact that the Bluetooth takes too long to restart, so I added a delay ;)
