### ISSUE TITLE
Using External BT hci1

### ISSUE THREAD

**Issue by Kalisabbb** [pentestfunctions/BlueDucky#4]
Hello nice work!!
I can't use with external BT adapter (hci1)  only works for hci0?
Saludos

**Comment by pentestfunctions** [comment]
Yes apologies just replace hci0 in the blueducky.py script on lines 599, 602 and 624 and it will work for you :)

**Comment by Kalisabbb** [comment]
Thank you I will try!

**Comment by Kalisabbb** [comment]
Thank you I change I now ..no errors but can't find devices...make scan but no find..
With hcitool scan for example ok...
It's for Kali Linux...

I'm using in android with NH..and amazing!!and fun! Thanx

**Comment by pentestfunctions** [comment]
Make sure you are in the bluetooth screen of the target device or have visibility on. Once you have the mac address, they don't need to be on that screen but sometimes they will need to be for it to be visible.

**Comment by Kalisabbb** [comment]
Thank you for you answer...yes I try in all modes...and not find any devices with hci1

Thanx!!
