### ISSUE TITLE
OSError: [Errno 19] No such device. how to fix it

### ISSUE THREAD

**Issue by djaberoff** [pentestfunctions/BlueDucky#41]
Attempting to scan now...
Traceback (most recent call last):
  File "/home/kali/BlueDucky/BlueDucky/BlueDucky.py", line 697, in <module>
    main()
  File "/home/kali/BlueDucky/BlueDucky/BlueDucky.py", line 637, in main
    target_address = get_target_address()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/BlueDucky/BlueDucky/utils/menu_functions.py", line 7, in get_target_address
    devices = scan_for_devices()
              ^^^^^^^^^^^^^^^^^^
  File "/home/kali/BlueDucky/BlueDucky/utils/menu_functions.py", line 126, in scan_for_devices
    nearby_devices = bluetooth.discover_devices(duration=8, lookup_names=True, flush_cache=True, lookup_class=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/PyBluez-0.30-py3.11-linux-x86_64.egg/bluetooth/bluez.py", line 19, in discover_devices
OSError: [Errno 19] No such device

please help me

**Comment by xensurve** [comment]
systemctl is-enabled bluetooth 

hcitool device

**Comment by coldvisionz** [comment]
> systemctl is-active bluetooth # check if bluetooth is running
> 
> hcitool device # lists your devices

also, bluetooth is disabled by default on kali distros

`sudo systemctl enable bluetooth
sudo systemctl start bluetooth`

**Comment by djaberoff** [comment]
> > systemctl is-active bluetooth # check if bluetooth is running
> > hcitool device # lists your devices
> 
> also, bluetooth is disabled by default on kali distros
> 
> `sudo systemctl enable bluetooth`
> 
> `sudo systemctl start bluetooth`

i turned it on and the same problem

**Comment by djaberoff** [comment]
> systemctl is-active bluetooth # check if bluetooth is running
> 
> hcitool device # lists your devices

i checked it and it said thats inactive and i turned it on then it said active but the same problem

**Comment by coldvisionz** [comment]
did you solve the problem ? 
can you share the whole output from the terminal and logs

**Comment by Alexalecos** [comment]
If you still have the problem half a year later, try sudo hciconfig hci0 up
