### ISSUE TITLE
E: Unable to locate package install ERROR

### ISSUE THREAD

**Issue by rasoolport** [pentestfunctions/BlueDucky#50]
E: Unable to locate package install error
while running 
sudo apt install -y python3-pydbus command

log
> sudo apt install -y git gcc python3-pip python3-setuptools \
> sudo apt install -y python3-pydbus
[sudo] password for kali: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package install
E: Unable to locate package install

**Comment by Lamentomori** [comment]
please try ```sudo apt-get update``` and try again.

**Comment by rasoolport** [comment]
Tried it.. Nothing changed

**Comment by rasoolport** [comment]
it was corrected in while doing it again
